export const classes = [
    {
      id: 1,
      name: "Class 1",
      capacity: 28,
      total: 30,
      level: 4,
      shift: "MWF",
      teacher: "Ahmad Sheriff",
    },
    {
      id: 2,
      name: "Class 2",
      capacity: 10,
      total: 30,
      level: 3,
      shift: "MWF",
      teacher: "Ali Alfiyu",
    },
    {
      id: 3,
      name: "Class 3",
      capacity: 30,
      total: 50,
      level: 2,
      shift: "MWF",
      teacher: "Ali Alfiyu",
    },
    {
      id: 4,
      name: "Class 4",
      capacity: 20,
      total: 50,
      level: 3,
      shift: "MWF",
      teacher: "Ali Alfiyu",
    },
    {
      id: 5,
      name: "Class 5",
      capacity: 20,
      total: 40,
      level: 4,
      shift: "MWF",
      teacher: "Ali Alfiyu",
    },
];